import { DocumentType } from '@sberauto/loanapplifecycledc-proto/public'

import { SubmitAction } from '../ClientForm.types'

export const EXPECTED_DATA = {
  additionalIncome: '1000.47',
  additionalNumber: '79033800013',
  averageIncome: '1000.45',
  hasNameChanged: true,
  numOfChildren: '5',
  familyStatus: 1,
  birthDate: new Date('2000-01-01T00:00:00.000Z'),
  birthPlace: 'Саратов',
  clientFormerName: 'Иванова Ивана Ивановна',
  clientName: 'Иванов Иван Иванович',
  divisionCode: '123-456',
  email: 'mail@mail.ru',
  emplNotKladr: false,
  employerAddress: {
    area: 'Усть-Курдюмский',
    areaType: '55',
    city: 'Москва',
    cityType: '77',
    house: '17',
    houseExt: '5',
    postalCode: '410055',
    regCode: '77',
    region: 'Москва',
    settlement: 'Курдюм',
    settlementType: '45',
    street: 'Севастопольская',
    streetType: '34',
    unit: 'ж',
    unitNum: '174',
  },
  employerAddressString:
    '410055 77 Москва 55 Усть-Курдюмский 77 Москва 45 Курдюм 34 Севастопольская 17 ж 5 174 ',
  employerInn: '123123123',
  employerName: 'ДрайвКликБанк',
  employerPhone: '79033800013',
  employmentDate: new Date('2021-09-08T07:44:00.355Z'),
  expenses: '12005.2',
  familyIncome: '44000.82',
  incomeConfirmation: false,
  incomeProofUploadValidator: '',
  issuedBy: 'МВД',
  livingAddress: {
    area: 'Усть-Курдюмский',
    areaType: '55',
    city: 'Москва',
    cityType: '77',
    house: '17',
    houseExt: '5',
    postalCode: '410055',
    regCode: '77',
    region: 'Москва',
    settlement: 'Курдюм',
    settlementType: '45',
    street: 'Севастопольская',
    streetType: '34',
    unit: 'ж',
    unitNum: '174',
  },
  livingAddressString:
    '410055 77 Москва 55 Усть-Курдюмский 77 Москва 45 Курдюм 34 Севастопольская 17 ж 5 174 ',
  livingNotKladr: false,
  mobileNumber: '79033800013',
  occupation: 2,
  passport: '1234 123456',
  passportDate: new Date('2023-12-15T00:00:00.000Z'),
  regAddrIsLivingAddr: true,
  regNotKladr: false,
  registrationAddress: {
    area: 'Усть-Курдюмский',
    areaType: '55',
    city: 'Москва',
    cityType: '77',
    house: '17',
    houseExt: '5',
    postalCode: '410055',
    regCode: '77',
    region: 'Москва',
    settlement: 'Курдюм',
    settlementType: '45',
    street: 'Севастопольская',
    streetType: '34',
    unit: 'ж',
    unitNum: '174',
  },
  registrationAddressString:
    '410055 77 Москва 55 Усть-Курдюмский 77 Москва 45 Курдюм 34 Севастопольская 17 ж 5 174 ',
  relatedToPublic: 1,
  secondDocumentDate: new Date('2023-12-15T00:00:00.000Z'),
  secondDocumentIssuedBy: 'МВД',
  secondDocumentNumber: '1234123456',
  secondDocumentType: 15,
  sex: 0,
  submitAction: 'save',
  bankStatementFile: undefined,
  questionnaireFile: undefined,
  ndfl3File: undefined,
  ndfl2File: {
    file: {
      dcAppId: '544545',
      documentType: DocumentType.TWO_NDFL,
      name: '2НДФЛ',
    },
    status: 'upload',
  },
  isFormComplete: false,
}

const EMPTY_ADDRESS = {
  postalCode: '',
  regCode: null,
  region: '',
  areaType: null,
  area: '',
  cityType: null,
  city: '',
  settlementType: null,
  settlement: '',
  streetType: null,
  street: '',
  house: '',
  unit: '',
  houseExt: '',
  unitNum: '',
}

export const EXPECTED_EMPTY_DATA = {
  clientName: '',
  hasNameChanged: false,
  clientFormerName: '',
  numOfChildren: '',
  familyStatus: null,
  passport: '',
  birthDate: null,
  birthPlace: '',
  passportDate: null,
  divisionCode: '',
  sex: null,
  issuedBy: '',
  registrationAddressString: '',
  registrationAddress: EMPTY_ADDRESS,
  regNotKladr: false,
  regAddrIsLivingAddr: false,
  livingAddressString: '',
  livingAddress: EMPTY_ADDRESS,
  livingNotKladr: false,
  mobileNumber: '',
  additionalNumber: '',
  email: '',
  averageIncome: '',
  additionalIncome: '',
  familyIncome: '',
  expenses: '',
  relatedToPublic: null,

  // Справки о доходах
  incomeConfirmation: false,
  ndfl2File: null,
  ndfl3File: null,
  bankStatementFile: null,
  incomeProofUploadValidator: '',

  secondDocumentType: null,
  secondDocumentNumber: '',
  secondDocumentDate: null,
  secondDocumentIssuedBy: '',
  occupation: null,
  employmentDate: null,
  employerName: '',
  employerPhone: '',
  employerAddress: EMPTY_ADDRESS,
  employerAddressString: '',
  emplNotKladr: false,
  employerInn: '',
  questionnaireFile: null,
  submitAction: SubmitAction.Save,
  isFormComplete: false,
}

const EMPTY_ADDRESS = {
  postalCode: '',
  regCode: null,
  region: '',
  areaType: null,
  area: '',
  cityType: null,
  city: '',
  settlementType: null,
  settlement: '',
  streetType: null,
  street: '',
  house: '',
  unit: '',
  houseExt: '',
  unitNum: '',
}

export const EXPECTED_EMPTY_DATA = {
  clientName: '',
  hasNameChanged: false,
  clientFormerName: '',
  numOfChildren: '',
  familyStatus: null,
  passport: '',
  birthDate: null,
  birthPlace: '',
  passportDate: null,
  divisionCode: '',
  sex: null,
  issuedBy: '',
  registrationAddressString: '',
  registrationAddress: EMPTY_ADDRESS,
  regNotKladr: false,
  regAddrIsLivingAddr: false,
  livingAddressString: '',
  livingAddress: EMPTY_ADDRESS,
  livingNotKladr: false,
  mobileNumber: '',
  additionalNumber: '',
  email: '',
  averageIncome: '',
  additionalIncome: '',
  familyIncome: '',
  expenses: '',
  relatedToPublic: null,

  // Справки о доходах
  incomeConfirmation: false,
  ndfl2File: null,
  ndfl3File: null,
  bankStatementFile: null,
  incomeProofUploadValidator: '',

  secondDocumentType: null,
  secondDocumentNumber: '',
  secondDocumentDate: null,
  secondDocumentIssuedBy: '',
  occupation: null,
  employmentDate: null,
  employerName: '',
  employerPhone: '',
  employerAddress: EMPTY_ADDRESS,
  employerAddressString: '',
  emplNotKladr: false,
  employerInn: '',
  questionnaireFile: null,
  submitAction: SubmitAction.Save,
}
