import { Application, StatusCode } from '@sberauto/loanapplifecycledc-proto/public'

export const dataMock: Application[] = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Михаил',
    lastName: 'Терентьев',
    middleName: 'Павлович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    status: StatusCode.STATUS_CODE_INITIAL,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    status: StatusCode.STATUS_CODE_PROCESSED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    status: StatusCode.STATUS_CODE_APPROVED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    status: StatusCode.STATUS_CODE_FINALLY_APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Виктор',
    lastName: 'Поляков',
    middleName: 'Николаевич',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    status: StatusCode.STATUS_CODE_FORMATION,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Галина',
    lastName: 'Смирнова',
    middleName: 'Васильевна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    status: StatusCode.STATUS_CODE_REJECTED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Елена',
    lastName: 'Крылова',
    middleName: 'Сергеевна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    status: StatusCode.STATUS_CODE_CANCELED_DEAL,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Максим',
    lastName: 'Морозов',
    middleName: 'Петрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    status: StatusCode.STATUS_CODE_CANCELED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мария',
    lastName: 'Вершинина',
    middleName: 'Владимировна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    status: StatusCode.STATUS_CODE_SIGNED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Иван',
    lastName: 'Афанасьев',
    middleName: 'Савельевич',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    status: StatusCode.STATUS_CODE_AUTHORIZED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Илья',
    lastName: 'Шевцов',
    middleName: 'Иванович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    status: StatusCode.STATUS_CODE_FINANCED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Маргарита',
    lastName: 'Реброва',
    middleName: 'Александровна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    status: StatusCode.STATUS_CODE_ERROR,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Анна',
    lastName: 'Сомова',
    middleName: 'Павловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    status: StatusCode.STATUS_CODE_APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Игорь',
    lastName: 'Ребров',
    middleName: 'Семенович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    status: StatusCode.STATUS_CODE_CANCELED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Антон',
    lastName: 'Зимовский',
    middleName: 'Владимирович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    status: StatusCode.STATUS_CODE_REJECTED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Андрей',
    lastName: 'Калугин',
    middleName: 'Николаевич',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    status: StatusCode.STATUS_CODE_APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
]

export const preparedMock = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Терентьев Михаил Павлович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_INITIAL,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Карасева Мелания Данииловна',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_PROCESSED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнов Александр Александрович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_APPROVED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_FINALLY_APPROVED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Поляков Виктор Николаевич',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_FORMATION,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнова Галина Васильевна',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_REJECTED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Крылова Елена Сергеевна',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_CANCELED_DEAL,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Морозов Максим Петрович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_CANCELED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Вершинина Мария Владимировна',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_SIGNED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Афанасьев Иван Савельевич',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_AUTHORIZED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Шевцов Илья Иванович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_FINANCED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Реброва Маргарита Александровна',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_ERROR,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Сомова Анна Павловна',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_APPROVED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Ребров Игорь Семенович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_CANCELED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Зимовский Антон Владимирович',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_REJECTED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Калугин Андрей Николаевич',
    isDC: true,
    source: 'Сбол',
    status: StatusCode.STATUS_CODE_APPROVED,
    vendorCode: '2003023272',
  },
]
