import { StatusCode, Application } from '@sberauto/loanapplifecycledc-proto/public'

export const dataMock: Application[] = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Михаил',
    lastName: 'Терентьев',
    middleName: 'Павлович',
    vendorCode: '2003023272',
    source: 'Sberbankru',
    decisionTerm: 10,
    status: StatusCode.INITIAL,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Sberbankru2',
    decisionTerm: 44,
    status: StatusCode.PROCESSED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Portalda',
    decisionTerm: 16,
    status: StatusCode.APPROVED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Sberbankrucall',
    decisionTerm: 10,
    status: StatusCode.FINALLY_APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Виктор',
    lastName: 'Поляков',
    middleName: 'Николаевич',
    vendorCode: '2003023272',
    source: 'Marketing',
    decisionTerm: 44,
    status: StatusCode.FORMATION,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Галина',
    lastName: 'Смирнова',
    middleName: 'Васильевна',
    vendorCode: '2003023272',
    source: 'broker_before_chat',
    decisionTerm: 16,
    status: StatusCode.REJECTED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Елена',
    lastName: 'Крылова',
    middleName: 'Сергеевна',
    vendorCode: '2003023272',
    source: 'broker_after_chat',
    decisionTerm: 10,
    status: StatusCode.CANCELED_DEAL,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Максим',
    lastName: 'Морозов',
    middleName: 'Петрович',
    vendorCode: '2003023272',
    source: 'sbol_after_chat',
    decisionTerm: 44,
    status: StatusCode.CANCELED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мария',
    lastName: 'Вершинина',
    middleName: 'Владимировна',
    vendorCode: '2003023272',
    source: 'autoteka',
    decisionTerm: 16,
    status: StatusCode.SIGNED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Иван',
    lastName: 'Афанасьев',
    middleName: 'Савельевич',
    vendorCode: '2003023272',
    source: 'autoru',
    decisionTerm: 10,
    status: StatusCode.AUTHORIZED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Илья',
    lastName: 'Шевцов',
    middleName: 'Иванович',
    vendorCode: '2003023272',
    source: 'avito',
    decisionTerm: 44,
    status: StatusCode.ISSUED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Маргарита',
    lastName: 'Реброва',
    middleName: 'Александровна',
    vendorCode: '2003023272',
    source: 'classified',
    decisionTerm: 16,
    status: StatusCode.ERROR,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Анна',
    lastName: 'Сомова',
    middleName: 'Павловна',
    vendorCode: '2003023272',
    source: 'broker',
    decisionTerm: 10,
    status: StatusCode.APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Игорь',
    lastName: 'Ребров',
    middleName: 'Семенович',
    vendorCode: '2003023272',
    source: 'DC',
    decisionTerm: 44,
    status: StatusCode.CANCELED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Антон',
    lastName: 'Зимовский',
    middleName: 'Владимирович',
    vendorCode: '2003023272',
    source: 'SBOL',
    decisionTerm: 16,
    status: StatusCode.REJECTED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Андрей',
    lastName: 'Калугин',
    middleName: 'Николаевич',
    vendorCode: '2003023272',
    decisionTerm: 10,
    status: StatusCode.APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
]

export const preparedMock = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 10,
    fullName: 'Терентьев Михаил Павлович',
    source: 'Сайт',
    status: StatusCode.INITIAL,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 44,
    fullName: 'Карасева Мелания Данииловна',
    source: 'Сайт',
    status: StatusCode.PROCESSED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 16,
    fullName: 'Смирнов Александр Александрович',
    source: 'PortalDA',
    status: StatusCode.APPROVED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 10,
    fullName: 'Медведев Али Денисович',
    source: 'ЕРКЦ',
    status: StatusCode.FINALLY_APPROVED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 44,
    fullName: 'Поляков Виктор Николаевич',
    source: 'RBC',
    status: StatusCode.FORMATION,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 16,
    fullName: 'Смирнова Галина Васильевна',
    source: 'СберАвто',
    status: StatusCode.REJECTED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 10,
    fullName: 'Крылова Елена Сергеевна',
    source: 'СберАвто',
    status: StatusCode.CANCELED_DEAL,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 44,
    fullName: 'Морозов Максим Петрович',
    source: 'СберАвто',
    status: StatusCode.CANCELED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 16,
    fullName: 'Вершинина Мария Владимировна',
    source: 'Автотека',
    status: StatusCode.SIGNED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 10,
    fullName: 'Афанасьев Иван Савельевич',
    source: 'Auto.ru',
    status: StatusCode.AUTHORIZED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 44,
    fullName: 'Шевцов Илья Иванович',
    source: 'Avito',
    status: StatusCode.ISSUED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 16,
    fullName: 'Реброва Маргарита Александровна',
    source: 'Дром',
    status: StatusCode.ERROR,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 10,
    fullName: 'Сомова Анна Павловна',
    source: 'СберАвто',
    status: StatusCode.APPROVED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 44,
    fullName: 'Ребров Игорь Семенович',
    source: 'ДЦ',
    status: StatusCode.CANCELED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 16,
    fullName: 'Зимовский Антон Владимирович',
    source: 'SBOL',
    status: StatusCode.REJECTED,
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: 10,
    fullName: 'Калугин Андрей Николаевич',
    source: '',
    status: StatusCode.APPROVED,
    vendorCode: '2003023272',
  },
]
