import { Application } from '@sberauto/loanapplifecycledc-proto/public'

export const dataMock: Application[] = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '44',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '16',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
    contractFinancedFlag: false,
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: '10',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
    contractFinancedFlag: false,
  },
]

export const preparedMock = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Карасева Мелания Данииловна',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнов Александр Александрович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Карасева Мелания Данииловна',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнов Александр Александрович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Карасева Мелания Данииловна',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнов Александр Александрович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Карасева Мелания Данииловна',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнов Александр Александрович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '44',
    fullName: 'Карасева Мелания Данииловна',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'canceled',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '16',
    fullName: 'Смирнов Александр Александрович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'rejected',
    vendorCode: '2003023272',
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    decisionTerm: '10',
    fullName: 'Медведев Али Денисович',
    isDC: true,
    source: 'Сбол',
    //@ts-ignore поправить в ветке со статусами
    status: 'approved',
    vendorCode: '2003023272',
  },
]
