import { Application, StatusCode } from '@sberauto/loanapplifecycledc-proto/public'

export const findApplicationsDataMock: Application[] = [
  {
    applicationNumber: '1',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Михаил',
    lastName: 'Терентьев',
    middleName: 'Павлович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 10,
    status: StatusCode.INITIAL,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '2',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мелания',
    lastName: 'Карасева',
    middleName: 'Данииловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 44,
    status: StatusCode.PROCESSED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '3',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Александр',
    lastName: 'Смирнов',
    middleName: 'Александрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 16,
    status: StatusCode.APPROVED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '4',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Али',
    lastName: 'Медведев',
    middleName: 'Денисович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 10,
    status: StatusCode.FINALLY_APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '5',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Виктор',
    lastName: 'Поляков',
    middleName: 'Николаевич',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 44,
    status: StatusCode.FORMATION,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '6',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Галина',
    lastName: 'Смирнова',
    middleName: 'Васильевна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 16,
    status: StatusCode.REJECTED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '7',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Елена',
    lastName: 'Крылова',
    middleName: 'Сергеевна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 10,
    status: StatusCode.CANCELED_DEAL,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '8',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Максим',
    lastName: 'Морозов',
    middleName: 'Петрович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 44,
    status: StatusCode.CANCELED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '9',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Мария',
    lastName: 'Вершинина',
    middleName: 'Владимировна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 16,
    status: StatusCode.SIGNED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '10',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Иван',
    lastName: 'Афанасьев',
    middleName: 'Савельевич',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 10,
    status: StatusCode.AUTHORIZED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '11',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Илья',
    lastName: 'Шевцов',
    middleName: 'Иванович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 44,
    status: StatusCode.ISSUED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '12',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Маргарита',
    lastName: 'Реброва',
    middleName: 'Александровна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 16,
    status: StatusCode.ERROR,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '13',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Анна',
    lastName: 'Сомова',
    middleName: 'Павловна',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 10,
    status: StatusCode.APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '14',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Игорь',
    lastName: 'Ребров',
    middleName: 'Семенович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 44,
    status: StatusCode.CANCELED,
    accountFlag: false,
    contractPrintFlag: true,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
  {
    applicationNumber: '15',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Антон',
    lastName: 'Зимовский',
    middleName: 'Владимирович',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 16,
    status: StatusCode.REJECTED,
    accountFlag: false,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: true,
  },
  {
    applicationNumber: '16',
    applicationUpdateDate: '22.02.2023',
    firstName: 'Андрей',
    lastName: 'Калугин',
    middleName: 'Николаевич',
    vendorCode: '2003023272',
    source: 'Сбол',
    decisionTerm: 10,
    status: StatusCode.APPROVED,
    accountFlag: true,
    contractPrintFlag: false,
    contractSignedFlag: false,
    contractFinancingFlag: false,
  },
]
